### PR TITLE
Sprites

### PR DESCRIPTION
**Pull request by DaniMorales97**
I added some background music and sound effects for the lasers. 

Also I simplified the main.py file adding a new game.py file where a class Game is defined with everything needed.

### CODE REVIEW

**Comment by Priyansh61** [comment]
hey I just want to know if you are free right now , there are some things which i would like to know regarding the code, so it would be great if you can help me figure them out.

One more thing i dont know the os.path.join are not working on my system so i had to make some changes to make them work, so let me know if the code used to work on your system.

**Comment by DaniMorales97** [comment]
Oh and I also added score and highscore. You can try it and tell me your highscore :wink:

**Comment by Priyansh61** [comment]
Hey do you use discord so that i can contact you out there?? regarding some more changes.

**Comment by DaniMorales97** [comment]
I just did another commit, fixed having enemies spawn on top of each other, had to modify the spawning probability and position too

**Comment by Priyansh61** [comment]
I dont know why all the enemy ships are shooting lasers , could you please point me to the code where i could make changes to the code so that not every enemy ship shoots and it just depends on the probability.

It makes the game really difficult since all the enemy ships are shooting laser so it will be easy if only certain number of enemy ship shoots the laser.

**Comment by DaniMorales97** [comment]
> Hey do you use discord so that i can contact you out there?? regarding some more changes.

Yeah, add me: Daniel Morales#2739

**Comment by DaniMorales97** [comment]
> I dont know why all the enemy ships are shooting lasers , could you please point me to the code where i could make changes to the code so that not every enemy ship shoots and it just depends on the probability.
> 
> It makes the game really difficult since all the enemy ships are shooting laser so it will be easy if only certain number of enemy ship shoots the laser.

Yeah you can find it inside the Enemy class, the shoot() method. I now it's difficult, I kinda intended it to be that way. However, there are several things we can change to make it easier if you want. It's a good idea to give them a probability to even shoot, but right now what I do is increase the cooldown, I think I increased it to 300 in last commit to make it a little easier, according to the changes I made to the probability of spawning.

I can add the probability to shoot if you want.

**Comment by DaniMorales97** [comment]
I found a bug. I forgot to add a line in the collisions() function that kills the enemy sprite when colliding with the player, it made the collision mean game over. It's okay now.

**Comment by DaniMorales97** [comment]
I just added a new commit, I changed how the background is displayed. Instead of it being an static image I created the Background class where each dot (or star) in the background is an instance of it. That way I can make them move downwards.

**Comment by DaniMorales97** [comment]
Oh also fixed enemies shooting before entering the screen. Those lasers disappeared automatically, but I noticed them because of the sound effect.

**Comment by DaniMorales97** [comment]
I had a great idea, make the dots in the background have random speeds, it gives it a depth effect and I think it looks awesome.

**Comment by DaniMorales97** [comment]
You made a commit before accepting the PR with all the changes. I see it is about the #8 issue you have with the file not being found. I would recommend you revert that commit and accept the PR, and if it continues not to work we can do the changes, but it should. 

We can do it all together in a discord call if you want

**Comment by Priyansh61** [comment]
Hey

Thanks for your awesome work @DaniMorales97 .

I have finally merged the PR after resolving all the conflicts and adding some more commits to resolve some issues.

The sound and the dynamci background is really cool and makes the game a lot fun to play.

Now I can't stop thinking about adding the remaing features.

Let's work on them and really thanks for all your hard work and efforts.

**Comment by DaniMorales97** [comment]
Your welcome. I'm really enjoying working in this project

**Pull request merged**
