### PR TITLE
fix #3 + typos etc.

### LINKED ISSUE #3: Game crashes due to empty laser list
`File "/home/priyansh/Python2/projects/space-invaders/main.py", line 268, in <module>
    menu()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 260, in menu
    main()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 248, in main
    redraw_window ()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 201, in redraw_window
    menu()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 260, in menu
    main()
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 239, in main
    player.move_laser(enemies,4)
  File "/home/priyansh/Python2/projects/space-invaders/main.py", line 106, in move_laser
    self.lasers.remove(laser)
ValueError: list.remove(x): x not in list`
<section>
  <h3>Error Generation:</h3>
  <p>The error is generated whenever you continuosly press the space bar to shoot the lasers.</p>
</section>
<section>
  <h3>Attempted Fixes :</h3>
  <p>Tried making if else statement so that the laser is not removed from the list when the size of the list is less than a particular size but this doesn't fix the issue.</p>
</section>

### PR DESCRIPTION
**Pull request by DaniMorales97**
fix #3

### CODE REVIEW

**Comment by Priyansh61** [comment]
Hey @DaniMorales97 

Could you please make a new PR or edit the same, changing the branch where you want to merge the PR from main to sprites so that we can keep both the approaches in different otherwise i have to merge this branch in the base branch.

So please edit or make a new PR, changing the target branch from main to sprites.

**Comment by Priyansh61** [comment]
And one more thing i saw the changes which you have made, they are really amazing now the code is  much more readabele and easily understandable.

Couldn't wait to add more amazing features in the game once the PR is merged.

**Comment by DaniMorales97** [comment]
> Hey @DaniMorales97
> 
> Could you please make a new PR or edit the same, changing the branch where you want to merge the PR from main to sprites so that we can keep both the approaches in different otherwise i have to merge this branch in the base branch.
> 
> So please edit or make a new PR, changing the target branch from main to sprites.

This is not the sprites branch that I'm trying to merge. Look at the changes, this is only some typos and PEP 8 compliance, apart from fixing bug #3 and another one I had loading the background.

The PR for sprites is the other one

**Comment by Priyansh61** [comment]
Hey 

I have merged your PR. 

Thank you so much for your time and efforts @DaniMorales97

**Comment by DaniMorales97** [comment]
No worries, I'm enjoying it and learning along the way so its great

**Pull request merged**
